---
name: lefty
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  shimmer: ^1.1.2
  flutter_spinkit: ^4.1.2
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  bot_toast: ^3.0.5
  cloud_firestore: ^0.16.0
  flutter_launcher_icons: ^0.8.1
  provider: null
  cupertino_icons: ^1.0.0
  curved_navigation_bar: ^0.3.7
  numberpicker: ^1.3.0
  image_picker: ^0.6.7+22
  firebase_storage: ^7.0.0
  cached_network_image: ^2.5.0
  google_maps_flutter: ^1.2.0
  http: ^0.12.0+1
  json_serializable: ^3.3.0
  location: ^3.2.4
  geolocator: ^6.2.0
  get: ^3.25.4
  shared_preferences: ^0.5.12+4
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
